### ISSUE TITLE
Package gem with active_record_migrations

### ISSUE THREAD

**Issue by fwolfst** [rosenfeld/active_record_migrations#15]
Hi,

this is probably more a StackOverflow question, if so, just give me a hint and close this issue.

I want to create a gem (call it `ar_models`) that contains some ActiveRecord-models and provides the means to setup and migrate the database. Then, other gems or projects can require that gem, run e.g. a rake Task to setup (or migrate) the database and happily use the model. (I am not talking about rails projects here).

Now, in `active_record_migrations` the migration files are picked up from `db/migrate` (although it can be changed in the options). Either I know the absolute path to the "installed" gem (`ar_models`) or I copy over the migration files. Is there a cleaner option that I do not see? As is, it renders the otherwise great active_record_migrations gem a bit useless for my purpose.

I.e. I want the "other gem" (call it `ar_model_user`) to be able to define database location and stuff, but not be concerned with the migration details.

Thanks for contributing, reading and responding.

**Comment by Smarre** [comment]
@fwolfst Sorry for shameless advertisement, but [I did a system for this for our company’s needs](https://github.com/Smarre/multi_ar). We have internal gem, where the migrations are. That gem has shallow binary which implements MultiAR’s interface class and shallow class which sets up the settings (defaults) we use and can be included in the projects for convenience.

**Comment by fwolfst** [comment]
@Smarre Great shameless advertisment :) If I understand correctly I would create my `ar_models` gem (it will have a cooler name) which depends on `multi_ar` and provides the migration and model definitions.

Then, the depending gem (`ar_model_user`) requires `ar_models`, has access to the models, means of migrating the database after version jumps and can define the database location itself? Sorry, I have not yet found the time to look carefully at its README and might not be able to play around a lot these days.

**Comment by rosenfeld** [comment]
@fwolfst you can provide multiple migrations paths actually. From each gem using `ar_models` you can call some code like this:

```ruby
ActiveRecordMigrations.configure{|c| c.migrations_paths << MY_GEM_PATH}
```

Just ensure this is executed before `ActiveRecordMigrations.load_taks` is called.

**Comment by Smarre** [comment]
@fwolfst Basically like that, yes.

Just a word of warning, since this was born from our internal needs (and still evolving that way), there may be some obvious missing features or bugs. I will fix them if you inform about them though. Documentation may be scarce too.

Looks like this project also supports multiple migration dirs, my project’s focus was multiple databases more than multiple migration dirs. So unless you need multiple databases, this may be better, I don’t think you’ll gain much from my project :)

**Comment by fwolfst** [comment]
@rosenfeld Thanks! I will try to find out how to find the currently requireds gems own path (I guess its somewhere in `Gem`. It has to work with relative pahts from `Gemfiles` as well as installed gems (which i usually pull in via Gemfile->gemspec and bundler)

**Comment by rosenfeld** [comment]
Or you can simply use something like this in you `lib/my-gem.rb`:

```ruby
MY_MIGRATIONS_PATH = File.join __dir__, '..', 'migrations'
```

Or something like that.

**Comment by fwolfst** [comment]
@rosenfeld Awesome, will try that when I find the time for that kind of coziness. Its true that this pattern is used here and there and thus should resolve reliably to the current codes location :).

**Comment by fwolfst** [comment]
@rosenfeld Great, that seems to work, thanks!
