### ISSUE TITLE
"Minor issue" regarding table ar_internal_metadata with release 6.1.1.1

### ISSUE THREAD

**Issue by bf39l** [rosenfeld/active_record_migrations#25]
Just point out a "minor issue" with release 6.1.1.1 or maybe just me OCD. 
When I ran this rake task `db=production rake db:migrate`  it did migrate for production database however in table 'ar_internal_metadata' it set 'enviroment' value to 'development'. That is due to missing rails env variable eg: RAILS_ENV=production

Currently my work around is creating ActiveRecordMigrations configure with following code
```
ActiveRecordMigrations.configure do |c|
  c.schema_format = :sql # default is :ruby
  # make sure table ar_internal_metadata would contain same environment information
  Rails.env = ENV['db'] || Rails.env
end
```

**Comment by rosenfeld** [comment]
Oh, I never noticed the environment was stored in the database. I don't actually rely on that ar_internal_metadata table for anything. Good catch, I'll merge it. Thanks.
