### ISSUE TITLE
Deprecation warning with AR 7

### ISSUE THREAD

**Issue by ddoherty03** [rosenfeld/active_record_migrations#28]
I get the following deprecation warning after upgrading to AR 7 from AR 6:

```
DEPRECATION WARNING: ActiveRecord::Base.schema_format= is deprecated and will be removed in Rails 7.1.
Use `ActiveRecord.schema_format=` instead.
 (called from <top (required)> at /home/ded/src/byr/Rakefile:46)
```

Looks like a simple fix.

**Comment by rosenfeld** [comment]
Hi @ddoherty03, I just returned from vacation. I'll take a look at it. Also, I'm no longer using AR migrations myself for a little while since I moved to using Sequel Migrations instead. So, if you or someone else would be interested in taking a maintenance role on this tool, just let me know.

**Comment by rosenfeld** [comment]
I just released a new version. Hopefully it should fix the warning. Please confirm it's working and I'll close the issue. Thanks for reporting.

**Comment by ddoherty03** [comment]
@rosenfeld, I just saw this fix.  Installed it, and the error went away, so that looks like it did the trick.  Many thanks.

**Comment by rosenfeld** [comment]
Awesome, thanks for confirming!
